# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be380c40be3d522f8914217a82d83ebc6a57c72666902ae0fdbb27f1fd453905a4b405d796624e49849a89831ca97ba3251f0c8991dfa532e5a474e747267968

test:
  secret_key_base: eae030857c3ab4978c918a3c51129dc6a00eb80c3dad2b55a2b964fdb16c6341f9a470292466b7b777ef2dbdca352b6f53f82a7d3150cf16a7b789a5e853b95b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
